/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    media: Media;
    posts: Post;
    consultas: Consulta;
    sponsors: Sponsor;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    consultas: ConsultasSelect<false> | ConsultasSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    numeros: Numero;
    servicios: Servicio;
    contacto: Contacto;
    home: Home;
  };
  globalsSelect: {
    numeros: NumerosSelect<false> | NumerosSelect<true>;
    servicios: ServiciosSelect<false> | ServiciosSelect<true>;
    contacto: ContactoSelect<false> | ContactoSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * El administrador gestiona usuarios. El editor edita el contenido del sitio y ve las consultas.
   */
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Ejemplo: optimizacion-envios-nacionales
   */
  slug: string;
  category: number | Category;
  featuredImage?: (number | null) | Media;
  isFeatured?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Título personalizado para motores de búsqueda (máx. 60 caracteres).
   */
  seoTitle?: string | null;
  /**
   * Resumen descriptivo para resultados de Google (150 - 160 caracteres).
   */
  seoDescription?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Si asignás una fecha futura, se programará automáticamente.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes que llegan por los formularios del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas".
 */
export interface Consulta {
  id: number;
  estado: 'nueva' | 'leida' | 'respondida' | 'cerrada';
  tipo: 'contacto' | 'publicidad';
  nombre: string;
  email: string;
  telefono?: string | null;
  empresa?: string | null;
  asunto?: string | null;
  /**
   * Solo se completa en las consultas que llegan por publicidad.
   */
  formato?: string | null;
  mensaje: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Marcas que aparecen en la seccion de sponsors de la home.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  nombre: string;
  /**
   * Preferentemente PNG o WEBP con fondo transparente.
   */
  logo: number | Media;
  /**
   * Se muestra debajo del logo. Por ejemplo: Seguridad, Banca Institucional.
   */
  categoria?: string | null;
  sitioWeb?: string | null;
  /**
   * Ajuste fino para que logos de proporciones distintas se vean parejos. Si el logo se ve chico, proba con Grande.
   */
  tamano: 'normal' | 'grande';
  /**
   * De menor a mayor. Los de numero mas bajo aparecen primero.
   */
  orden: number;
  /**
   * Destildar para sacarlo de la web sin borrar la ficha.
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'consultas';
        value: number | Consulta;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  isFeatured?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultas_select".
 */
export interface ConsultasSelect<T extends boolean = true> {
  estado?: T;
  tipo?: T;
  nombre?: T;
  email?: T;
  telefono?: T;
  empresa?: T;
  asunto?: T;
  formato?: T;
  mensaje?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  nombre?: T;
  logo?: T;
  categoria?: T;
  sitioWeb?: T;
  tamano?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Las cifras que se repiten a lo largo de la home.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros".
 */
export interface Numero {
  id: number;
  /**
   * Se escribe tal cual se muestra, con el signo mas si corresponde.
   */
  puestos: string;
  personasDiarias: string;
  empleos: string;
  /**
   * A confirmar con el cliente: hasta ahora la web decia 30+ arriba y 25+ mas abajo.
   */
  aniosTrayectoria: string;
  diasActividad: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tarifas de internet y estacionamiento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios".
 */
export interface Servicio {
  id: number;
  internet: {
    diario: {
      precio: string;
      moneda: string;
      detalle: string;
    };
    mensual: {
      precio: string;
      moneda: string;
      detalle: string;
    };
  };
  alquiler?: {
    /**
     * Se muestran como lista en la seccion de alquiler. El orden de esta lista es el orden en que se ven.
     */
    condiciones?:
      | {
          titulo: string;
          detalle: string;
          id?: string | null;
        }[]
      | null;
  };
  estacionamiento: {
    precio: string;
    moneda: string;
    titulo: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datos que aparecen en la seccion de contacto, el pie y el boton flotante.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacto".
 */
export interface Contacto {
  id: number;
  direccion: string;
  email: string;
  horarios: string;
  whatsapp: {
    /**
     * Con codigo de pais y sin espacios ni signos. Es el que usa el enlace.
     */
    numero: string;
    visible: string;
    /**
     * Es el texto que aparece ya escrito cuando alguien abre el chat.
     */
    mensaje: string;
  };
  /**
   * Es un contacto distinto al general: atiende consultas de alquiler de puestos. Aparece en la seccion de servicios.
   */
  whatsappAlquiler: {
    numero: string;
    mensaje: string;
  };
  redes?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Que secciones aparecen en la portada y en que orden. El menu, la portada, el contacto y el pie son fijos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Arrastra para reordenar. Sacar una seccion no borra su contenido: vuelve a aparecer si la agregas de nuevo.
   */
  secciones?:
    | (
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'cifras';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'historia';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'lineaDeTiempo';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'streaming';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'visita';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicios';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'impacto';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'comercio';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'sponsors';
          }
        | {
            cantidad: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'novedades';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeros_select".
 */
export interface NumerosSelect<T extends boolean = true> {
  puestos?: T;
  personasDiarias?: T;
  empleos?: T;
  aniosTrayectoria?: T;
  diasActividad?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios_select".
 */
export interface ServiciosSelect<T extends boolean = true> {
  internet?:
    | T
    | {
        diario?:
          | T
          | {
              precio?: T;
              moneda?: T;
              detalle?: T;
            };
        mensual?:
          | T
          | {
              precio?: T;
              moneda?: T;
              detalle?: T;
            };
      };
  alquiler?:
    | T
    | {
        condiciones?:
          | T
          | {
              titulo?: T;
              detalle?: T;
              id?: T;
            };
      };
  estacionamiento?:
    | T
    | {
        precio?: T;
        moneda?: T;
        titulo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacto_select".
 */
export interface ContactoSelect<T extends boolean = true> {
  direccion?: T;
  email?: T;
  horarios?: T;
  whatsapp?:
    | T
    | {
        numero?: T;
        visible?: T;
        mensaje?: T;
      };
  whatsappAlquiler?:
    | T
    | {
        numero?: T;
        mensaje?: T;
      };
  redes?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  secciones?:
    | T
    | {
        cifras?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        historia?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        lineaDeTiempo?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        streaming?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        visita?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        servicios?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        impacto?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        comercio?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        sponsors?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        novedades?:
          | T
          | {
              cantidad?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}